language: python
sudo: required
dist: trusty
python:
  - "2.7"
services:
  - couchdb
env:
  global:
  - TZ=Europe/Kiev
  matrix:
  - SANDBOX_MODE=
  - SANDBOX_MODE=True
cache:
  directories:
    - eggs
before_install:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get update
  - sudo apt-get install libsodium-dev -y
  - sh bootstrap.sh
install:
  - bin/buildout -N
  - bin/buildout -N remotes:branch=$TRAVIS_BRANCH
  - bin/develop up --force
script:
  - bin/py.test ./openprocurement/tender/competitivedialogue/tests --cov=openprocurement.tender.competitivedialogue
  - bin/pylint --errors-only --disable=no-member,not-an-iterable,bad-super-call,unsubscriptable-object,too-many-format-args openprocurement.tender.competitivedialogue
after_success:
  - bin/coveralls
